### ISSUE TITLE
last order item in customer order mail is missing

### ISSUE THREAD

**Issue by tabsl** [mollie/mollie-oxid#23]
We have had the problem for months that the last order item is missing from the customer order confirmation only for Mollie orders.

This is also not present in the history entry (plain order confirmation).

However, this is present in the admin order confirmation. It is also present in the order.

We have already created several tickets with mollie support, but none of them have been really/completely processed there.

**Comment by proudcommerce** [comment]
We also have this problem! Any progress?

**Comment by mediarex-de** [comment]
This Problem also exist at Klarna Module …

**Comment by hwysoszynski** [comment]
Hi everyone,

Thank you for your messages.

I've discussed this issue with our integration partner, but unfortunately, we couldn't reproduce the behaviour in our clean test environments. @mediarex-de, you mentioned that this issue also exists in the Klarna Module. Can you reproduce the issue with the Mollie Plugin if the Klarna Plugin is deactivated or uninstalled?

To investigate further and address this properly, please report the issue to our Mollie Support team. They should be able to narrow down the problem. Feel free to mention that I've referred you.

Thank you for your help! 

Best regards,
Helge Wysoszynski
Integration Manager

**Comment by reyneke-vosz** [comment]
We got the issue as well. 

We cannot confirm it 100%, but it seems to happen when articles run out of stock.

Example: An article is on stock three times, customer orders all three of them. Then the order will be executed correctly, but the article is not visible in the customer e-mail anymore. 

We got angry mails from customers, because they think that the article is not available anymore and they want their money back. In reality the order is correct, but the article is not listed in the confirmation e-mail.

We got the issue as well. 

We cannot confirm it 100%, but it seems to happen when articles run out of stock when buying them.

Example: An article is on stock three times, customer orders all three of them, then the order will be executed correctly, but the article is not visible in the customer e-mail anymore.

**Comment by tabsl** [comment]
I just tested it again ...

![tm2208081558004554](https://github.com/user-attachments/assets/e9490253-18b4-4a8f-84b1-ad31fef628d7)

item was still in stock twice (order status: cannot be ordered if sold out)
--> error message after returning to the shop from Mollie (normally order confirmation page)
--> item missing in order confirmation email (admin and customer)

![tm2208081600004555](https://github.com/user-attachments/assets/2cf38778-5658-4152-aca8-8b243ebfdd92)

it looks like someone is trying to buy the item again but the stock has already been reduced

**Comment by mediarex-de** [comment]
It is Not a Problem in combination of Klarna and mollie Module as same time activ / installed. Problem also exist if only one of Booth Modulen is installed and active

**Comment by tabsl** [comment]
> Problem also exist if only one of Booth Modulen is installed and active
so seems that klarna module also has an problem ...

**Comment by FatchipRobert** [comment]
The issue should be fixed with this commit.

The order process is sent through the big finalizeOrder methode twice in the module. (before redirect and after)
With non-redirect payments it's only being sent there once.

The stock check happens at the beginning of finalizeOrder and sets the order object in a certain state where further down the process no second stock check is happening.

When the customer returns to the shop after a redirect payment with Mollie the order was not in this state where no further stock check is done.
In that case the order confirmation email process did another stock check, which would not happen normally.

This won't heppen anymore with the fix.

This wasn't reproducable in a standard oxid installation, because the "Users have to confirm terms and conditions for downloadable and intangible products during the check-out" checkbox in the backend also puts the order in this needed state where no further stock check is done and this checkbox is on by default. But when disabled, this error can happen.
